steps:
  # pull latest code and test
  # only lang-specic step
  - name: "golang:latest"
    id: Test
    entrypoint: /bin/sh
    args: ["-c", "export GO111MODULE=on", "go mod download", "go test ./... -v"]

  # build image
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_APP_NAME}:${SHORT_SHA}", "."]

  # push image to gcr
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: ["push", "gcr.io/${PROJECT_ID}/${_APP_NAME}:${SHORT_SHA}"]

  # update manifest with few env var (mainly release tag)
  - name: "gcr.io/cloud-builders/gcloud"
    id: Deploy
    args: ["beta", "run", "deploy", "${_APP_NAME}",
      "--image", "gcr.io/${PROJECT_ID}/${_APP_NAME}:${SHORT_SHA}",
      '--region', "${_CLUSTER_REGION}",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--set-env-vars", "RELEASE=${SHORT_SHA}"]

tags: ["run", "demo"]
