apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: APP_NAME
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/PROJECT_ID/APP_NAME:IMAGE_SHA
            env:
            - name: RELEASE
              value: "RELEASE_TAG"