name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: Cloud Run Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Build Docker image
        uses: actions/docker/cli@master
        with:
          args: "build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/maxprime"

      - name: Authenticate into Google Cloud Platform
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Configure Docker to use Google Cloud Platform
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker --quiet"

      - name: Push image to Google Cloud Container Registry
        uses: actions/gcloud/cli@master
        with:
          entrypoint: sh
          args: -c "docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/maxprime"

      - name: Install beta commands and deploy on cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy maxprime --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/maxprime --project ${{ secrets.GCLOUD_PROJECT }} --region us-central1 --platform managed"
